const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
const GET_BY_ID = "GET_BY_ID";
const SORT_SETTINGS = "SORT_SETTINGS";
const RESET_SETTINGS = "RESET_SETTINGS";

export {
    GET_ALL_COUNTRIES,
    GET_BY_ID,
    SORT_SETTINGS,
    RESET_SETTINGS,
};